### PR TITLE
Fix page title for check your answers page

### PR DESCRIPTION
**Pull request by lfdebrux**
Ticket: https://trello.com/c/zzrRBDzm/1365-page-title-on-brief-response-check-your-answers-page-doesnt-match-content

The page title should be the same as the page heading, and different from the page title for other pages

### CODE REVIEW

**Comment by katstevens** [comment]
Can we add a quick test assertion somewhere in here? https://github.com/alphagov/digitalmarketplace-brief-responses-frontend/blob/master/tests/app/main/test_briefs.py#L1323

**Comment by katstevens** [comment]
Also just noticed that the final breadcrumb item won't be correct on the success page either....

**Comment by lfdebrux** [comment]
> Also just noticed that the final breadcrumb item won't be correct on the success page either....

I'm not sure the same template is used for the success page, there is also a separate success page template (which had the same page title), https://github.com/alphagov/digitalmarketplace-brief-responses-frontend/blob/master/app/templates/briefs/application_submitted.html

So I'm not sure why the check answers page has the title/heading logic.

I will fix the breadcrumb though.

**Comment by katstevens** [comment]
> So I'm not sure why the check answers page has the title/heading logic.

Ah - suppliers can still go back and review/edit their answers for `submitted` brief responses up until the deadline - that's when this template is used.

**Pull request merged**
